// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXy1xIhH4WhAoxbeOiRWCWIrJnB0qT9EI',
    appId: '1:243032132710:web:ef70fe0c6a2bc8f1ab31a7',
    messagingSenderId: '243032132710',
    projectId: 'login-signup-firebase-9a8a4',
    authDomain: 'login-signup-firebase-9a8a4.firebaseapp.com',
    storageBucket: 'login-signup-firebase-9a8a4.appspot.com',
    measurementId: 'G-J433FKN56K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXVP33tBRidU5xT1XCmY5JaSwIzQEib30',
    appId: '1:243032132710:android:794b66e7cd0e7c89ab31a7',
    messagingSenderId: '243032132710',
    projectId: 'login-signup-firebase-9a8a4',
    storageBucket: 'login-signup-firebase-9a8a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIadGJX2Vvy1Atsb4s2xaP4Rnmq4xbU9s',
    appId: '1:243032132710:ios:5c75589b1adeea0eab31a7',
    messagingSenderId: '243032132710',
    projectId: 'login-signup-firebase-9a8a4',
    storageBucket: 'login-signup-firebase-9a8a4.appspot.com',
    iosClientId: '243032132710-efvkj4nn605cbchqhjo9lfv1sg4nfcsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoSoginSignupFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIadGJX2Vvy1Atsb4s2xaP4Rnmq4xbU9s',
    appId: '1:243032132710:ios:2a4eccecaacfe19aab31a7',
    messagingSenderId: '243032132710',
    projectId: 'login-signup-firebase-9a8a4',
    storageBucket: 'login-signup-firebase-9a8a4.appspot.com',
    iosClientId: '243032132710-hu03a9bo7104tgc4ct9f4fsnat3u7hfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoSoginSignupFirebase.RunnerTests',
  );
}
